// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/","parentId":"1","id":"2"},"3":{"path":"/game-commands","parentId":"1","id":"3"},"4":{"path":"/about","parentId":"1","id":"4"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__GameCommands" */'@/pages/GameCommands.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__about" */'@/pages/about.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'C:/Users/korra/Downloads/SPOILER_AnantaTestGameServer2.0/AnantaTestGameServer2.0/ananta-gateway-control/src/layouts/index.tsx')),
},
  };
}
