gBanId = {
	WAIT_MESSAGE = -12,
	RESTAURANT_MANAGER = -4,
	SPOON_COMMON_FORBIDDEN = -1,
	CLAW_MACHINE_MANAGER = -2,
	COMMON_INFO_PANELS = -13,
	DIALOG_MANAGER = -7,
	MAID_TEA = -6,
	SGUI_NAVIGATION = -8,
	TIMER = -9,
	UI_LOADING = -15,
	GUIDE = -18,
	SWITCH_SCENE = -3,
	TIMELINE = -11,
	APPLICATION_FOCUS = -14,
	ONLINE_WATCHING = -16,
	HACK_CAMERA_PANEL = -17,
	DEBUG = -10,
	PET_ANIMAL_PREPARE = -5
}

return gBanId
