gBlackScreenId = {
	RESTAURANT_INVITE = -19,
	CHALLENGE_RANK_PANEL = -23,
	SPOON_SET_SCREEN_BLACK = -15,
	SWITCH_TELEPORT = -20,
	POLICE_EXAMINE = -21,
	CLEAVER_BLACK_SCREEN = -13,
	CLEAVER_ENABLE_CARRIER = -14,
	CLAW_MACHINE_MANAGER = -9,
	TELEPORT = -4,
	VIDEO = -17,
	SPOON_TASK = -5,
	SPOON_TWEEN_BLACK = -10,
	LING_MODEL = -11,
	POLICE_HELICOPTER = -24,
	AFTER_SWITCH_SCENE_SHOW = -22,
	SPOON_SET_SCREEN_BLACK_AUTO = -16,
	TIMELINE = -3,
	LUA_SLOT_CHECK_INTERACTION = -12,
	CLEAVER_TWEEN_BLACK = -8,
	WAIT_FOR_SWITCH_SCENE = -6,
	LOADING = -18,
	BIG_WORLD_MERGE = -7,
	DIALOG_CAMERA_TEMPLATE = -2
}

return gBlackScreenId
