gInputActionId = {
	UIGPINTERACTION_KEYBOARD1 = 5,
	UICOMMON_SCROLL = 2,
	UICOMMON_SCROLL_RIGHT = 3,
	UIGPINTERACTION_KEYBOARDESC = 7,
	UIGPINTERACTION_KEYBOARD3 = 8,
	MOVEMENT_MOVE = 1,
	UIGPINTERACTION_KEYBOARDTAB = 9,
	UIBIGMAP_FASTACTION_1 = 11,
	UIBIGMAP_SCALE = 10,
	UIGPINTERACTION_KEYBOARD2 = 6,
	UICOMMON_TOUCHSCREEN = 4
}

return gInputActionId
