gShowSceneControlId = {
	CLAW_MACHINE_MANAGER = -2,
	UI_MODEL_CAMERA = -6,
	SPOON_COMMON_FORBIDDEN = -8,
	RESTAURANT_MANAGER = -4,
	CHAIR_RACE = -10,
	CAMERA_GESTURE = -7,
	PET_ANIMAL_TWO = -3,
	SPOON_RESTAURANT_BAN = -5,
	CLEAVER_COMMON = -9,
	DIALOG_MANAGER = -11
}

return gShowSceneControlId
