gDisplayMessageId = {
	SELECT_WITH_CLOSE = 26,
	TRIPLE_SELECT = 32,
	SELECT_FORCE = 28,
	QUEUE = 1,
	SELECT_WITH_CHECKBOX_DNOTSHOWAGAIN = 30,
	CONFIRM_FORCE = 29,
	SELECT_WITH_CHECKBOX = 31,
	CONFIRM = 8,
	DEBUG = 6,
	SELECT = 7
}

return gDisplayMessageId
