C_InventoryItemDetailInfoPackageTemplateStore = DefClass("C_InventoryItemDetailInfoPackageTemplateStore", C_InventoryItemDetailInfoPackageTemplateStore, C_InventoryItemDetailInfoTemplateStore)
GroupName2Class.InventoryItemDetailInfoPackageTemplateStore = C_InventoryItemDetailInfoPackageTemplateStore
local M = C_InventoryItemDetailInfoPackageTemplateStore
