local M = gHudMgr
local EnemyHUDCtrl = require("LX6/Manager/HUD/EnemyHUDCtrl")
local PlayerHUDCtrl = require("LX6/Manager/HUD/PlayerHUDCtrl")
local NpcHUDCtrl = require("LX6/Manager/HUD/NpcHUDCtrl")
local DestructibleHUDCtrl = require("LX6/Manager/HUD/DestructibleHUDCtrl")
local SlotEntityHUDCtrl = require("LX6/Manager/HUD/SlotEntityHUDCtrl")
local VehicleHUDCtrl = require("LX6/Manager/HUD/VehicleHUDCtrl")
local AetherHUDCtrl = require("LX6/Manager/HUD/AetherHUDCtrl")
M.MinNpcVisibleDist = 10
M.NameBarShowDist = 20
M.ExtraDist = 2
M.HUDTargetType = LX6.GUI.HUDNew.HUDTargetType
M.HUDTemplateType = LX6.GUI.HUDNew.HUDTemplateType
M.TemplateType2Store = {
	[M.HUDTemplateType.EnemyHpBar] = "EnemyHpTemplate",
	[M.HUDTemplateType.EnemyPartShieldBar] = "EnemyWeaponShieldBarTemplate",
	[M.HUDTemplateType.DistanceAttackMarker] = "DistanceAttackMarkerTemplate",
	[M.HUDTemplateType.BVB] = "BVBTemplate",
	[M.HUDTemplateType.BuffHeadIcon] = "BuffHeadIconTemplate",
	[M.HUDTemplateType.EnemyPosition] = "EnemyPositionTemplate",
	[M.HUDTemplateType.StealthDetectValue] = "StealthDetectValueTemplate",
	[M.HUDTemplateType.DangerHint] = "DangerHintTemplate",
	[M.HUDTemplateType.NpcName] = "NpcNameTemplate",
	[M.HUDTemplateType.NpcTitle] = "NpcTitleTemplate",
	[M.HUDTemplateType.NpcIcon] = "NpcFeatureIconTemplate",
	[M.HUDTemplateType.NPCAIChatting] = "NPCAIChattingTemplate",
	[M.HUDTemplateType.DebugText] = "DebugTextTemplate",
	[M.HUDTemplateType.SlotTopInfo] = "SlotTopInfoTemplate",
	[M.HUDTemplateType.PlayerName] = "PlayerNameTemplate",
	[M.HUDTemplateType.LevitationBar] = "LevitationBarTemplate",
	[M.HUDTemplateType.PlayerIdentifiedNumber] = "PlayerNumberIconTemplate",
	[M.HUDTemplateType.TopIcon] = "TopIconTemplate",
	[M.HUDTemplateType.TopText] = "TopTextTemplate",
	[M.HUDTemplateType.DangerIcon] = "EnemyDangerIconTemplate",
	[M.HUDTemplateType.TopAnimIcon] = "TopAnimIconsTemplate"
}
M.TemplateType2Name = {
	hpBar = M.HUDTemplateType.EnemyHpBar,
	partBar = M.HUDTemplateType.EnemyPartShieldBar,
	missileLock = M.HUDTemplateType.DistanceAttackMarker,
	BVB = M.HUDTemplateType.BVB,
	buffIcon = M.HUDTemplateType.BuffHeadIcon,
	enemyPos = M.HUDTemplateType.EnemyPosition,
	detect = M.HUDTemplateType.StealthDetectValue,
	dangerHint = M.HUDTemplateType.DangerHint,
	npcName = M.HUDTemplateType.NpcName,
	npcTitle = M.HUDTemplateType.NpcTitle,
	npcIcon = M.HUDTemplateType.NpcIcon,
	npcAIChat = M.HUDTemplateType.NPCAIChatting,
	debug = M.HUDTemplateType.DebugText,
	slotTopInfo = M.HUDTemplateType.SlotTopInfo,
	playerName = M.HUDTemplateType.PlayerName,
	Levitation = M.HUDTemplateType.LevitationBar,
	PlayerNum = M.HUDTemplateType.PlayerIdentifiedNumber,
	TopIcon = M.HUDTemplateType.TopIcon,
	TopText = M.HUDTemplateType.TopText,
	dangerIcon = M.HUDTemplateType.DangerIcon,
	topAnimIcon = M.HUDTemplateType.TopAnimIcon
}
M.HUDTargetType2Ctrl = {
	[M.HUDTargetType.Enemy] = EnemyHUDCtrl,
	[M.HUDTargetType.Player] = PlayerHUDCtrl,
	[M.HUDTargetType.Npc] = NpcHUDCtrl,
	[M.HUDTargetType.Destruct] = DestructibleHUDCtrl,
	[M.HUDTargetType.SlotEntity] = SlotEntityHUDCtrl,
	[M.HUDTargetType.Vehicle] = VehicleHUDCtrl,
	[M.HUDTargetType.Aether] = AetherHUDCtrl
}
M.OnCreateFunc = {
	[M.HUDTemplateType.EnemyHpBar] = "OnCreateEnemyHpBar",
	[M.HUDTemplateType.EnemyPartShieldBar] = "OnCreateEnemyPartShieldBar",
	[M.HUDTemplateType.DistanceAttackMarker] = "OnCreateDistanceAttackMarker",
	[M.HUDTemplateType.BVB] = "OnCreateBVBTemplate",
	[M.HUDTemplateType.BuffHeadIcon] = "OnCreateBuffHeadIcon",
	[M.HUDTemplateType.EnemyPosition] = "OnCreateEnemyPosition",
	[M.HUDTemplateType.StealthDetectValue] = "OnCreateStealthDetectValue",
	[M.HUDTemplateType.DangerHint] = "OnCreateDangerHint",
	[M.HUDTemplateType.NpcName] = "OnCreateNpcName",
	[M.HUDTemplateType.NpcTitle] = "OnCreateNpcTitle",
	[M.HUDTemplateType.NpcIcon] = "OnCreateNpcIcon",
	[M.HUDTemplateType.NPCAIChatting] = "OnCreateNPCAIChatting",
	[M.HUDTemplateType.DebugText] = "OnCreateDebugText",
	[M.HUDTemplateType.SlotTopInfo] = "OnCreateSlotTopInfo",
	[M.HUDTemplateType.PlayerName] = "OnCreatePlayerName",
	[M.HUDTemplateType.LevitationBar] = "OnCreateLevitationBar",
	[M.HUDTemplateType.PlayerIdentifiedNumber] = "OnCreatePlayerIdentifiedNumber",
	[M.HUDTemplateType.TopIcon] = "OnCreatCommonTopIcon",
	[M.HUDTemplateType.TopText] = "OnCreatCommonTopText",
	[M.HUDTemplateType.DangerIcon] = "OnCreatDangerIcon",
	[M.HUDTemplateType.TopAnimIcon] = "OnCreatTopAnimIcon"
}
M.DebugTag = {
	VehicleInfo = "VehicleInfo",
	ToughnessNum = "ToughnessNum",
	DamAndDefNum = "DamAndDefNum",
	AIAction = "AIAction",
	Id = "Id",
	LevelNum = "LevelNum",
	ShieldNum = "ShieldNum",
	HpNum = "HpNum"
}
M.TopAnimType = {
	Gift = 0
}
