gDialogType = {
	REMOTE_CALL_CLIENT = 9,
	FORMAL_WITH_IMAGE = 16,
	BUBBLE_CLIENT = 18,
	FORMAL = 14,
	VIDEO_CLIENT = 19,
	VEHICLE_GAME = 20,
	FILM_SUBTITLE_CLIENT = 15,
	VIDEO_CLIENT_MULTI_MOVE = 22,
	FREE_CAMERA = 23,
	GAMEPLAY = 10,
	BLACK = 8,
	FILM_SUBTITLE = 13,
	REMOTE_CALL = 11,
	VIDEO_CLIENT_MOVE = 21,
	LOGIC_ONLY = 12
}

return gDialogType
