// <auto-generated>
// Base generated from client 4229938, synchronized here to the 4229938
// RPCDeserializeAuto.lua wire schema supplied with this server build.
// Do not reorder fields: UxSerializer writes public fields in declaration order.
// </auto-generated>
#nullable enable
using Ananta.SDK.Serialization;

namespace Ananta.Server.RpcTypes.Client4229938.Auto;

[UxContract]
internal sealed class AchievementDetail
{
    public double AchieveTime;
    public byte Status;
}

[UxContract]
internal sealed class BadgeInfo
{
    public uint TemplateId;
    public bool Active;
    public bool DropSend;
}

[UxContract]
internal sealed class ChallengeRecord
{
    public uint ChallengeId;
    public uint HighestLevel;
    public uint ReceivedRewardLevel;
    public int BestScore;
    public int CurrentScore;
    public uint CurrentRewardLevel;
    public bool CurrentIsNewRewardLevel;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<int, double> BestStatisticalData = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<int, double> CurrentStatisticalData = new();
}

[UxContract]
internal sealed class ChargeClientInfo
{
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> ChargedIds = new();
}

[UxContract]
internal sealed class ChatInfoList
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<NpcChatItem> ChatList = new();
    public uint Gameplay;
}

[UxContract]
internal sealed class ChefRecipeInfo
{
    public bool Unlock;
}

[UxContract]
internal sealed class ChefUnlockInfo
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ChefRecipeInfo>? RecipeDict;
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ChefSubRecipeInfo>? SubRecipeDict;
    public float ChefCollectionProgress;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<int> ReceivedCollectionRewards = new();
}

[UxContract]
internal sealed class ChefSubRecipeInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<int> UnlockedDimensions = new();
    public int UnlockFailCount;
    public int PityTriggerCount;
    public uint BestRank;
    public float BestScore;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> ReceivedRewards = new();
}

[UxContract]
internal sealed class ClientClubTaskInfo
{
    public uint WeeklyTime;
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ClubTaskInfo> TaskDict = new();
}

[UxContract]
internal sealed class ClientNpcChatData
{
    public uint TemplateId;
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<NpcChatItem> InviteChatList = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<NpcChatItem> DialogChatList = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ChatInfoList> NpcChatListDict = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ChatInfoList> DialogChatListDict = new();
}

[UxContract]
internal sealed class ClientNpcGroupChatData
{
    public uint TemplateId;
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<NpcChatItem> InviteChatList = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<NpcChatItem> DialogChatList = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> Members = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ChatInfoList> NpcChatListDict = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ChatInfoList> DialogChatListDict = new();
}

[UxContract]
internal sealed class ClientTuiteInfo
{
    public uint CfgId;
    public uint PublishTime;
    public bool IsCollect;
    public bool IsLike;
    public bool IsFollow;
    public bool HasTimeline;
    public TuiteTimelineData? TimelineData;
    public int LikeCount;
    public int ViewCount;
    public int CommentCount;
    public uint DropId;
    public string? OssKey;
}

[UxContract]
internal sealed class ClubTaskInfo
{
    public uint TaskId;
    public uint Count;
}

[UxContract]
internal sealed class CompoundStationClientInfo
{
    public uint Level;
}

[UxContract]
internal sealed class CompoundUseClientInfo
{
    public uint UsedCount;
}

[UxContract]
internal sealed class ComputerDetailInfo
{
    public uint CfgId;
    public uint FirstOpenTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> DeleteFiles = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> DeleteEmails = new();
}

[UxContract]
internal sealed class ComputerEmail
{
    public uint CfgId;
    public bool IsRead;
    public uint UnlockTime;
}

[UxContract]
internal sealed class ComputerFile
{
    public uint CfgId;
    public uint UnlockTime;
    public bool IsRead;
}

[UxContract]
internal sealed class ComputerUnlockInfo
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ComputerEmail>? UnlockEmails;
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ComputerFile>? UnlockFiles;
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ComputerDetailInfo>? ComputerInfos;
}

[UxContract]
internal sealed class CreditInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> CreditByType = new();
    public uint Level;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> ClaimedLevelRewards = new();
}

[UxContract]
internal sealed class DataLayerIndic
{
    public byte Mode;
    public int SceneBaseIndic;
    public int UniverseBaseIndic;
    public int RaidBaseIndic;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<int>? ResourceIndices;
}

[UxContract]
internal sealed class DisableBadgeInfos
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, DisableBadgeReasons> DisableBadgeInfoList = new();
}

[UxContract]
internal sealed class DisableBadgeReasons
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<int> ReasonList = new();
}

[UxContract]
internal sealed class DropLimitInfo
{
    public uint Count;
    public uint FinishTime;
}

[UxContract]
internal sealed class EmojiData
{
    public string Id = string.Empty;
    public uint Count;
}

[UxContract]
internal sealed class EnterSceneInfo
{
    // Field set/order must match the 4229938 EnterSceneInfo (dump TypeDefIndex
    // 32467): the 4229938 SpoonLevels/SpoonMd5s lists are gone in this build and
    // SectorControlIds/DynamicLayerId/DataLayerIndices/Seamless plus the three
    // nullable tail fields were added. Extra or missing fields desync the
    // client's Lua reader (SceneManager.OnSyncEnterScene #DataLayerIndices).
    public ulong PlayerSessionId;
    public uint RaidId;
    public ulong InstanceId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    public float Facing;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<string>? SceneSpoonNames;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<string>? SceneSpoonMd5s;
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Struct)]
    public List<SpiritInitData> Spirits = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public ServerSimpleGridInfo GridInfo = new();
    public uint MatchGameId;
    public uint SwitchShowId;
    public bool IsSwitchSpiritShow;
    public uint UniverseId;
    public uint SectorControlId;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> SectorControlIds = new();
    public uint DynamicLayerId;
    public LoadingTypeInfo LoadingType = new();
    public LinkSimpleInfo LinkSimpleInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<DataLayerIndic> DataLayerIndices = new();
    public bool Seamless;
    public PlayerCollectionRoomInfo? CollectionRoomLoadData;
    public PlayerHouseLoadData? HouseLoadData;
    [UxCollection(Count = UxCountEncoding.Int7)]
    // SceneManager passes this directly to SwitchSceneData.dungeonLoadSectorHashs;
    // null causes SwitchSceneManager.OnSyncEnterScene to throw before loading begins.
    public int[] TombIslandIds = [];
}

[UxContract]
internal sealed class PlayerCollectionRoomInfo
{
}

[UxContract]
internal sealed class PlayerHouseLoadData
{
}

[UxContract]
internal sealed class EventIdInfo
{
    public uint Id;
    public uint NpcId;
    public byte EventType;
}

[UxContract]
internal sealed class EventProgress
{
    public uint Value;
}

[UxContract]
internal sealed class EventProgressInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Struct)]
    public List<EventProgress> EventProgressDict = new();
    public uint Value;
}

[UxContract]
internal sealed class ExtractionShooterBagInfo
{
    public uint BagId;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<ExtractionShooterItemInfo> ItemInfoList = new();
}

[UxContract]
internal sealed class ExtractionShooterBringOutBudget
{
    public uint Amount;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ExtractionShooterSetTrackInfo> SetTracks = new();
}

[UxContract]
internal sealed class ExtractionShooterItemInfo
{
    public uint Id;
    public uint StackCount;
    public uint CellX;
    public uint CellY;
    public bool IsRotated;
    public bool IsLocked;
    public ulong BindPid;
    public float ShieldValue;
    public WeaponData? WeaponData;
    public ExtractionShooterCollectionBook? CollectionBook;
}

[UxContract]
internal sealed class ExtractionShooterSlotGroupInfo
{
    public uint BagId;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<ExtractionShooterItemInfo> ItemInfoList = new();
    public uint AddUnlockedCount;
    public uint AddMaxCapacity;
}

[UxContract]
internal sealed class FactionInfo
{
    public int Disposition;
    public uint DispositionLevel;
    public int Influence;
    public uint InteractionCount;
    public uint GreetCount;
    public bool IsUnlock;
    // Client 4229938 declares this complex field as non-null. A null marker makes
    // SyncPlayerInfo fail native parameter deserialization before world entry.
    public FactionCounterAttackData CounterAttackData = new();
}

[UxContract]
internal sealed class FanBoxDropInfo
{
    public int AwardScore;
    public uint LastUpdateTime;
    public uint WeekDropCount;
    public uint DropCount;
}

[UxContract]
internal sealed class FashionColoringInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<byte, uint> ColoringType2ColorIdDict = new();
}

[UxContract]
internal sealed class FashionCustomSuitSchemeInfo
{
    public string? SchemeName;
    public bool JoinRandomPool;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionInfo> WearFashionInfoList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionEditInfo>? WearFashionEditInfoList;
    public byte HiddenParts;
    public byte EditedHiddenParts;
}

[UxContract]
internal sealed class FashionFunctionSuitSchemeInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionInfo> WearFashionInfoList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionEditInfo>? WearFashionEditInfoList;
    public byte HiddenParts;
    public byte EditedHiddenParts;
}

[UxContract]
internal sealed class FashionInfo
{
    public uint FashionId;
    public uint ExpiredTime;
    public uint GainTime;
    public byte Status;
    public byte ApplyColoringSchemeId;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<byte, FashionColoringInfo> ColoringSchemeInfoDict = new();
    public byte UnlockColoringSlotCount;
    public uint ColoringSchemeTopNMaxCollectionScore;
    public int OwnedCount;
}

[UxContract]
internal sealed class FishInfo
{
    public uint UniqueId;
    public uint TemplateId;
    public float Weight;
    public float Length;
    public FishPlacedInfo? PlacedInfo;
}

[UxContract]
internal sealed class FishingGearInfo
{
    public uint UniqueId;
    public uint TemplateId;
    public uint RemainingDurability;
}

[UxContract]
internal sealed class FurnitureInfo
{
    public uint FurnitureId;
    public uint Count;
    public uint PlacedCount;
}

[UxContract]
internal sealed class HUDRecommendInfo
{
    public uint ConfigId;
    public uint ExpireTime;
    public bool Read;
    public uint OfflineRemaining;
}

[UxContract]
internal sealed class HouseFashionShowcaseData
{
    public uint FurnitureId;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, HouseFashionShowcaseModel> Models = new();
}

[UxContract]
internal sealed class HouseFashionShowcaseModel
{
    public uint FashionInstanceId;
    public uint ShowcaseId;
    public SpiritWearFashionsInfo FashionData = new();
}

[UxContract]
internal sealed class HouseFenestrationData
{
    public uint Type;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 CenterWS = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 DirectionWS = new();
    public uint PrefabID;
    public ulong PlacedInstanceId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector2Int Edge = new();
    public ulong GadgetInstanceId;
}

[UxContract]
internal sealed class HouseFloorsData
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Struct)]
    public Dictionary<ulong, HouseWallFloorValue> Floors = new();
}
[UxContract]
internal sealed class HouseFurniturePlacementStatistics
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> FurniturePlacedCountDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> SubTypePlacedCountDict = new();
}

[UxContract]
internal sealed class HouseInfo
{
    public uint HouseId;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<int, uint> ParkingSpaceVehicleIdDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, IndoorBuildInfo> FloorBuildInfoDict = new();
    public ulong CurPlacedFurnitureInstanceId;
    public HouseWallInfo WallInfo = new();
    public PlayerSingleHouseConfiguration Configuration = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<ulong, HouseFashionShowcaseData> FashionShowcaseDict = new();
    public HouseFurniturePlacementStatistics PlacementStatistics = new();
}

[UxContract]
internal sealed class HouseWallEdgeTexData
{
    public uint Left;
    public uint Right;
}

[UxContract]
internal sealed class HouseWallEdgeValue
{
    public uint Tag;
    public HouseWallEdgeTexData? Tex;
}

[UxContract]
internal sealed class HouseWallFloorMaskData
{
    public uint HypoTenuseMaskA;
    public uint HypoTenuseMaskB;
}

[UxContract]
internal sealed class HouseWallFloorTexData
{
    public uint Top;
    public uint Bottom;
}

[UxContract]
internal sealed class HouseWallFloorValue
{
    public HouseWallFloorMaskData? Mask;
    public HouseWallFloorTexData? Tex;
}

[UxContract]
internal sealed class HouseWallInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Struct)]
    public Dictionary<int, UXVector3> Nodes = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Struct)]
    public Dictionary<ulong, HouseWallEdgeValue> Edges = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Struct)]
    public Dictionary<string, HouseWallFloorValue> Floors = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<ulong, HouseFenestrationData> FenestrationDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<int, HouseFloorsData> FloorsByLevel = new();
}
[UxContract]
internal sealed class HousesInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<HouseInfo> OutdatedHouses = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> NotParkingSpaceVehicleIdList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FurnitureInfo> FurnitureInfoDict = new();
    public PlayerHouseConfiguration Configuration = new();
    public uint NextFashionInstanceId;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<HouseMetadata> HouseMetadataList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<HouseActiveInfo> HouseInfoList = new();
    public uint LastOrphanScanTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<ulong, bool> HouseLikesToday = new();
    public uint LastLikeResetTime;
    public uint NextFurnitureIndex;
}

[UxContract]
internal sealed class HouseActiveInfo
{
    public uint HouseId;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<int, uint> ParkingSpaceVehicleIdDict = new();
    public uint Version;
    public HouseSocialInfo? SocialInfo;
    public uint FurnitureIndex;
}

[UxContract]
internal sealed class HouseSocialInfo
{
    public string PromoImageUrl = string.Empty;
    public string WelcomeText = string.Empty;
}

[UxContract]
internal sealed class IndoorBuildInfo
{
    public PlacedFurnitureInfo Root = new();
}

[UxContract]
internal sealed class ItemCountLimitInfo
{
    public uint ItemId;
    public uint Count;
    public uint NextRefreshTime;
}

[UxContract]
internal sealed class ItemShortcutInfo
{
    public ulong UniqueId;
    public uint TemplateId;
}

[UxContract(TypeMark = 1)]
internal sealed class LinkSimpleInfo
{
    public ulong Id;
    public byte Mode;
    public byte DeviceLevel;
    public byte Tag;
    public uint PublicEventId;
    public uint LastPublicEventTime;
    public ulong HostPid;
}

[UxContract]
internal sealed class LoadingTextInfo
{
    public uint TemplateId;
    public uint LeftTimes;
}

[UxContract(TypeMark = 1)]
internal sealed class LoadingTypeInfo
{
    public byte Type;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<ulong>? Members;
    public bool Ripple;
}

[UxContract]
internal sealed class MallCartItemInfo
{
    public uint CommodityId;
    public uint Count;
    public uint AddTime;
}

[UxContract]
internal sealed class MallCommodityInfo
{
    public uint BoughtCount;
    public uint NextRefreshTime;
}

[UxContract]
internal sealed class MallInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, MallCommodityInfo> CommodityInfoDict = new();
    public PlayerMonthlyPassInfo PlayerMonthlyPassInfo = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<MallCartItemInfo> CartItemList = new();
}

[UxContract]
internal sealed class MapPin
{
    public uint RaidId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    public byte Type;
    public bool PosAdjusted;
}

[UxContract]
internal sealed class MartialArtistSlotInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> Slots = new();
}

[UxContract]
internal sealed class MeccaGrandpaBuildInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<MeccaGrandpaSlotInfo> Slots = new();
    public bool IsBuilt;
}

[UxContract]
internal sealed class MeccaGrandpaPartInfo
{
    public uint PartId;
    public uint Count;
}

[UxContract]
internal sealed class MeccaGrandpaSlotInfo
{
    public uint PartType;
    public uint PartId;
}

[UxContract]
internal sealed class MiniGameData
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> MiniGame_Bee = new();
}

[UxContract]
internal sealed class ModuleEventProgressInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ModuleEventProgressInfoBySpirit> ProgressInfoDict = new();
}

[UxContract]
internal sealed class ModuleEventProgressInfoBySpirit
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, EventProgressInfo> EventProgressInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> FinishedTemplateIdList = new();
}

[UxContract]
internal sealed class MonthlyPassInfo
{
    public uint Id;
    public uint ExpiredTime;
    public uint LastDailyRewardTime;
    public bool IsAutoPopup;
    public uint CumulativeLoginDays;
    public uint SwitchOffDays;
}

[UxContract]
internal sealed class MoveActionGroundData
{
    public byte MoveGroundType;
    public ulong MoveGroundId;
    public byte MetaInfo;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 LocalPos = new();
}

[UxContract]
internal sealed class NewChallengeRecord
{
    public uint ChallengeId;
    public uint HighestLevel;
    public uint ReceivedRewardLevel;
    public bool CurrentIsNewRewardLevel;
    public float BestScore;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> ParamData = new();
}

[UxContract]
internal sealed class NpcCardInfo
{
    public uint TemplateId;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint>? UnlockedVoice;
    public uint ActivateTimestamp;
    public double Favor;
    public uint InteractDays;
    public uint LastInteractTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> GroupNpcPhotoPosList = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> SingleNpcPhotoPosList = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> TodayChatPosList = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> FirstChatPosList = new();
    public uint PreferCfgId;
    public bool AcquireDropReward;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> ActiveGiftTags = new();
    public double MaxFavorInHistory;
    public uint TodayFavorDialogCount;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> InteractedStories = new();
    public bool HasUninteractedNpcVoice;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> InteractedVoices = new();
    public int FavorLevelReward;
    public bool HasNoInteractedStory;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint>? UnlockedStoryDict;
}

[UxContract]
internal sealed class NpcChatContext
{
    public uint BubbleId;
    public uint AcquireCfgId;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<EmojiData> EmojiList = new();
    public string? Url;
    public uint ActivityCfgId;
}

[UxContract]
internal sealed class NpcChatItem
{
    public uint Timestamp;
    public uint ChatId;
    public uint NextChatId;
    public NpcChatContext? ChatContext;
    public bool IsRead;
    public uint BelongNpc;
    public uint ChatActionTriggeredTime;
}

[UxContract]
internal sealed class NpcEventQueue
{
    public uint TodayTriggeredCount;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> EventIds = new();
}

[UxContract]
internal sealed class NpcEventQueueList
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, NpcEventQueue> NpcQueues = new();
    public uint TodayTriggeredCount;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, EventIdInfo> IdToNpcDict = new();
    public uint LastTriggerTime;
}

[UxContract]
internal sealed class NpcScheduleInfo
{
    public uint ActivityId;
    public int StartDaySecond;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    public int SpoonAgentId;
    public int EndDaySecond;
    public uint RaidId;
}

[UxContract]
internal sealed class NpcTimeTableInfo
{
    public NpcScheduleInfo Schedule0 = new();
    public NpcScheduleInfo Schedule1 = new();
    public NpcScheduleInfo Schedule2 = new();
    public NpcScheduleInfo Schedule3 = new();
    public NpcScheduleInfo Schedule4 = new();
    public int CurrentSpoonAgentId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 SpoonPosition = new();
    public NpcScheduleInfo? TempSchedule;
    public bool IsTempScheduleOnly;
    public long RefreshDay;
}

[UxContract]
internal sealed class OCControllerByte9Value
{
    public byte Value1;
    public byte Value2;
    public byte Value3;
    public byte Value4;
    public byte Value5;
    public byte Value6;
    public byte Value7;
    public byte Value8;
    public byte Value9;
}

[UxContract]
internal sealed class OCInfo
{
    public uint CreateTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<ushort, byte> ControllerByteValues = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Struct)]
    public Dictionary<ushort, OCControllerByte9Value> ControllerByte9Values = new();
    public string speech_id = string.Empty;
    public uint FashionOCId;
    public SpiritWearFashionsInfo? SpiritWearFashionsInfo;
    public ulong OCId;
    public string name = string.Empty;
    public string gender = string.Empty;
    public string? age;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<string> labels = new();
    public string description = string.Empty;
    public string story = string.Empty;
    public string identity = string.Empty;
    public string SpeechName = string.Empty;
    public uint SelectBodyTypeId;
    public string? SpeakingStyle;
    public string? Relationship;
    public string? DialogSample;
}
[UxContract]
internal sealed class OCMeccaGrandpaInfo
{
    public ulong RefOCId;
}

[UxContract]
internal sealed class OCMemoryEntry
{
    public uint MemoryId;
    public uint UnlockTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, string> ParamsDict = new();
}

[UxContract]
internal sealed class OCMemoryInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<byte, OCMemorySetData> MemorySetDataDict = new();
}

[UxContract]
internal sealed class OCMemorySetData
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, OCMemoryEntry> MemoryEntryDict = new();
    public uint RecoveredMemoryWeight;
}

[UxContract]
internal sealed class OCSpeechInfo
{
    public string SpeechName = string.Empty;
    public uint CreateTime;
    public string ExternalSpeechId = string.Empty;
    public SoundEffectConfig? SoundEffectConfig;
}

[UxContract]
internal sealed class OtherPlayerSpiritWearFashionsInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FashionColoringInfo>? WearFashionColoringInfoDict;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionInfo> WearFashionInfoList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionEditInfo>? WearFashionEditInfoList;
    public byte HiddenParts;
    public byte EditedHiddenParts;
}

[UxContract]
internal sealed class PendingGiftEntry
{
    public ulong GiftId;
    public ulong SenderPid;
    public uint CommodityId;
    public uint BundleId;
    public uint SendTime;
    public uint ExpireTime;
    public string GiftMessage = string.Empty;
    public byte HandleStatus;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<GiftPaidItem> PaidItems = new();
}

[UxContract]
internal sealed class PendingSeasonReward
{
    public uint SeasonId;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> TaskRewardDropIds = new();
    public uint TaskRewardProgress;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> LevelRewardDropIds = new();
}

[UxContract]
internal sealed class PersonalZoneHeadInfo
{
    public byte HeadType;
    public uint SystemHeadId;
    public uint AvatarFrame;
}

[UxContract]
internal sealed class PhoneContact
{
    public string Remark = string.Empty;
    public string PhoneNumber = string.Empty;
}

[UxContract]
internal sealed class PhoneContactCallRecord
{
    public uint CallTime;
    public byte CallType;
    public string PhoneNumber = string.Empty;
}

[UxContract]
internal sealed class PhoneContactGroup
{
    public string Name = string.Empty;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<string> PhoneNumberList = new();
}

[UxContract]
internal sealed class PhoneInfos
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PhoneContact> ContactList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PhoneContactGroup> ContactGroupList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PhoneContactCallRecord> CallRecordList = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<string, uint> ContactOutgoingCallTimesDict = new();
}

[UxContract]
internal sealed class PlacedFurnitureInfo
{
    public uint FurnitureId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Rotation = new();
    public ulong GadgetInstanceId;
    public ulong PlacedInstanceId;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<ulong, PlacedFurnitureInfo> ChildrenDict = new();
}

[UxContract]
internal sealed class PlanningBoardInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, byte> StepId2OptionIndexDict = new();
}

[UxContract]
internal sealed class PlayerBuffLibraryEntry
{
    public ulong EntryId;
    public uint LibraryCfgId;
    public long StartTimeMs;
    public long TotalDurationMs;
    public long ConsumedMs;
    public long LastTickAnchorMs;
    public string? SourceTag;
}

[UxContract]
internal sealed class PlayerCityPediaInfos
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, byte> CityPediaStatusDict = new();
    public CreditInfo CreditInfo = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FishRecordInfo> FishRecordDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> CreditedFurnitureDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> CreditedLootDict = new();
}

[UxContract]
internal sealed class PlayerClientInfo
{
    [UxBuffer(Count = UxCountEncoding.Int7)]
    public byte[] Config = Array.Empty<byte>();
    public PlayerClientInfoLogin InfoLogin = new();
    public PlayerClientInfoItem InfoItem = new();
    public PlayerClientInfoSpirit InfoSpirit = new();
    public PlayerClientInfoMinor InfoMinor = new();
    public PlayerClientInfoAchievement InfoAchievement = new();
}

[UxContract]
internal sealed class PlayerClientInfoAchievement
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SceneFogMap>? SceneFogMaps;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> SceneFogMapPoiIds = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> UnlockedCountryList = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> UnlockedQuestList = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, uint> CompletedSubQuestCnt = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ChallengeRecord> ChallengeRecordInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, NewChallengeRecord> NewChallengeRecordInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<int> FirstKillEnemyRecord = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> UnlockInvestigateGalleryList = new();
    public int InvestigateGalleryRedCnt;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, uint> CountryReputationInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FactionInfo> FactionInfoDic = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> OccupiedInfluenceArea = new();
    // Auto.Client 4229938 has no NullableAttribute on this field. Keep an empty
    // concrete object instead of emitting a null complex marker.
    public ClientFactionInfo ClientFactionInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, AchievementDetail> AchievementInfos = new();
}

[UxContract]
internal sealed class PlayerClientInfoAtmosphereGameplay
{
    public int PartTimeJobDailyRewardTimes;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint>? PartTimeJobUnlockStore;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, uint> WorldLifeDropLimit = new();
}

[UxContract]
internal sealed class PlayerClientInfoGuide
{
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> FinishedGuides = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> NewGuideTeachInfos = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> RewardedGuideTeachInfos = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> UnlockSystems = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<ushort>? TaskTitleGuideUnlockList;
}

[UxContract]
internal sealed class PlayerClientInfoItem
{
    public double Money;
    public double Gold;
    public double BindingGold;
    public double FreeGold;
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PlayerItemDayCount> ItemDayCounts = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PlayerPackItem> PackItems = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<byte, ItemShortcutInfo> ItemShortcutDic = new();
    public uint DestructibleShortcut;
    public uint TodayGachaCount;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, int> GachaPoolCount = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<ItemCountLimitInfo> ItemCountLimitInfoList = new();
    public uint QuantumWalletStartTime;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 PortalPosition = new();
    public uint PortalRaidId;
}

[UxContract]
internal sealed class PlayerClientInfoLogin
{
    public int Aid;
    public ulong Pid;
    public string AccountId = string.Empty;
    public string Name = string.Empty;
    public uint Level;
    public byte Sex;
    public PersonalZoneHeadInfo PzHeadInfo = new();
    public PersonalZoneHeadInfo LinkPzHeadInfo = new();
    public bool UseSystemName;
    public uint LastLeaveClubTime;
    public uint UniverseId;
    public uint LastChangeNameTime;
}

[UxContract]
internal sealed class PlayerClientInfoMinor
{
    public long Exp;
    public long Fan;
    public uint Fan12;
    public uint Fan123;
    public int YesterdayFan;
    public int WeeklyFanGrowth;
    public uint Level;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> LevelRewards = new();
    public uint StageLv;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, uint> ReceivedStageLvRewards = new();
    public int Questionnaire;
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, DropLimitInfo> DropLimitCount = new();
    public ChargeClientInfo ChargeInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<ulong, MapPin> MapPins = new();
    public MiniGameData MiniGame = new();
    public PlayerClientInfoGuide PlayerInfoGuide = new();
    public PlayerClientInfoNpcCultivation InfoNpcCultivation = new();
    public PlayerClientInfoNpcProfile InfoNpcProfile = new();
    public PlayerClientInfoAtmosphereGameplay PlayerInfoAtmosphereGameplay = new();
    public PlayerFashionsInfo PlayerFashionsInfo = new();
    public PlayerRadioSongsData PlayerRadioSongsData = new();
    public HousesInfo housesInfo = new();
    public PlayerPhoneClientInfo PlayerPhoneInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<byte, ModuleEventProgressInfo> ModuleEventProgressInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<byte, ModuleEventProgressInfo> UniverseModuleEventProgressInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, LoadingTextInfo> LoadingTexts = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, BadgeInfo> Badges = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<SpiritGroupChatInfo> GroupChats = new();
    public PlayerVehicleInfo VehicleInfo = new();
    public PlayerMatchInfo MatchInfo = new();
    public PlayerInfoPopularity PopularityInfoNew = new();
    public ComputerUnlockInfo ComputerUnlockInfo = new();
    public PlayerInteractionActionInfo PlayerInteractionActionInfo = new();
    public PlayerCityPediaInfos PlayerCityPediaInfos = new();
    public bool DebugReserveGpuDumps;
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, NpcTimeTableInfo>? FavorNpcDailyScheduleInfos;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, string> PlayerInterActionInfo = new();
    public PlanningBoardInfo PlanningBoardInfo = new();
    public MallInfo MallInfo = new();
    public PlayerLinkPlanningBoardInfo PlayerLinkPlanningBoardInfo = new();
    public PlayerGachaInfos PlayerGachaInfos = new();
    public PlayerClientInspireHubInfo PlayerInspireHubInfo = new();
    public PlayerExtractionShooterInfo PlayerExtractionShooterInfo = new();
    public PlayerOCInfo PlayerOCInfo = new();
    public PlayerTuiteClientInfo PlayerTuiteInfo = new();
    public PlayerInfoMartialArtist playerMartialArtistInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritTalentInfo> GameplayTalentInfos = new();
    public PlayerClientInfoSubmitItem InfoSubmitItem = new();
    public PlayerCompoundClientInfo InfoCompound = new();
    public PlayerOnlineSeasonProgressClientInfo InfoOnlineSeasonProgress = new();
    public PlayerTradeInfo PlayerTradeInfo = new();
    public PlayerGiftInfo PlayerGiftInfo = new();
    public ClientClubTaskInfo PlayerClubTaskInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, HUDRecommendInfo> HUDRecommendDict = new();
    public ChefUnlockInfo ChefUnlockInfo = new();
    public PlayerFishingInfo FishingInfo = new();
    public PlayerSettingInfo SettingInfo = new();
    public PlayerInstrumentInfo InstrumentInfo = new();
    public PlayerMeccaGrandpaPartsInfo PlayerMeccaGrandpaPartsInfo = new();
    public PlayerWeaponSkinInfo PlayerWeaponSkinInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, uint> GadgetDropLimitInfo = new();
    public PlayerScenarioInfos PlayerScenarioInfos = new();
    public PlayerLikeInfo PlayerLikeInfo = new();
    // 4229938 client treats this complex field as required during SyncPlayerInfo.
    public PlayerBasketballAppearanceInfo PlayerBasketballAppearanceInfo = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, uint> DropControlCountDict = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<BeggarAiPainting> BeggarAiPaintings = new();
    // 4229938 client reads ChatInfo as a required complex value as well.
    public PlayerChatInfo ChatInfo = new();
}

[UxContract]
internal sealed class PlayerClientInfoNpcCultivation
{
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<NpcCardInfo> NpcCardInfos = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<NpcCardInfo> LockedCardInfos = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<ClientNpcChatData> NpcChats = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<ClientNpcGroupChatData> NpcGroupChats = new();
    public uint AvailableGiftSendCount;
    public uint InteractPoint;
    public NpcEventQueueList NpcEventQueueList = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, uint> ChatGroupRenameDict = new();
}

[UxContract]
internal sealed class PlayerClientInfoNpcProfile
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, TrustNpcInfo> NpcProfiles = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> ProgressRewards = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, NpcProfileWebProgress> ProgressRewardsWithWeb = new();
}

[UxContract]
internal sealed class PlayerClientInfoPolice
{
    public uint TodayCompleteMissionCnt;
}

[UxContract]
internal sealed class PlayerClientInfoSpirit
{
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<SpiritInfo> Spirits = new();
    public PlayerInfoPokemon InfoPokemon = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> AvailableSkinParts = new();
    public PlayerInfoArmory InfoArmory = new();
    public uint ActiveSpirit;
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, DisableBadgeInfos> DisableBadgeInfosDict = new();
    public PlayerInfoFightStyle InfoFightStyle = new();
    public uint CommonSpiritTalentExp;
    public uint SpiritInitTalentPointAdd;
    public PlayerClientInfoPolice InfoPolice = new();
    public uint SexTransitionLastTime;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> InstalledApps = new();
}

[UxContract]
internal sealed class PlayerClientInfoSubmitItem
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SubmitItemData> SubmitItemDataDict = new();
}

[UxContract]
internal sealed class PlayerClientInspireHubInfo
{
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, int> TodayGamePlayJoinCountDict = new();
}

[UxContract]
internal sealed class PlayerCompoundClientInfo
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, CompoundStationClientInfo> StationDataDict = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, CompoundUseClientInfo> UseRecords = new();
}

[UxContract]
internal sealed class PlayerExtractionShooterInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ExtractionShooterBagInfo> Bags = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ExtractionShooterBringOutBudget> BringOutFunds = new();
    public uint TokenCount;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, ExtractionShooterSlotGroupInfo> SlotGroups = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> UnlockedExpansionIds = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> UnlockedBagIds = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> GamePlayTypeTotalBringOutIncome = new();
}

[UxContract]
internal sealed class PlayerFashionsInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritFashionsInfo> SpiritFashionsInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FashionInfo> FashionInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> FavoriteFashionIdList = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> FavoriteFashionSuitIdList = new();
    public bool DefaultSpiritIsInitDefaultFashion;
    public uint ColoringCollectionScore;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FashionSuitInstanceInfo> FashionSuitInstanceDict = new();
}

[UxContract]
internal sealed class PlayerFishingGameplayInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerFishingSpotPool> SpotPools = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> SpotLastRefreshTime = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> SpotLastResetTime = new();
}

[UxContract]
internal sealed class PlayerFishingInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FishingGearInfo> GearDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FishInfo> ConsumableFishDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FishInfo> OrnamentalFishDict = new();
    public uint NextUniqueId;
    public PlayerFishingGameplayInfo GameplayInfo = new();
}

[UxContract]
internal sealed class PlayerFishingSpotFish
{
    public uint Id;
    public uint FishConfigId;
    public float SpawnTime;
    public float Weight;
    public float Length;
}

[UxContract]
internal sealed class PlayerFishingSpotPool
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerFishingSpotFish> Fishes = new();
}

[UxContract]
internal sealed class PlayerGachaGroupInfo
{
    public uint TotalDrawCount;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> ClaimedMilestoneCounts = new();
}

[UxContract]
internal sealed class PlayerGachaInfos
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerGachaPoolInfo> PoolInfos = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerGachaGroupInfo> GroupInfos = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerGachaPityInfo> PityInfos = new();
}

[UxContract]
internal sealed class PlayerGachaPityInfo
{
    public uint DrawsSinceLastReset;
    public uint TotalDrawCount;
}

[UxContract]
internal sealed class PlayerGachaPoolInfo
{
    public uint DrawCount;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> WonItemIds = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<GachaDrawRecord> DrawRecords = new();
}

[UxContract]
internal sealed class PlayerGameInfo
{
    public uint MultiPlayerId;
    public byte State;
}

[UxContract]
internal sealed class PlayerGiftInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PendingGiftEntry> UnclaimedGifts = new();
    public bool IsGiftOwnedInitialized;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PendingGiftEntry> HandledGifts = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<ulong> RefundedGiftIds = new();
}

[UxContract]
internal sealed class PlayerGuitarInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<int> ChordIds = new();
    public int rhythmA;
    public int rhythmB;
}

[UxContract]
internal sealed class PlayerHouseCameraConfiguration
{
    public float MoveSpeed;
    public float SpinSpeed;
    public float ZoomSpeed;
}

[UxContract]
internal sealed class PlayerHouseConfiguration
{
    public PlayerHouseCameraConfiguration Camera = new();
}

[UxContract]
internal sealed class PlayerInfoArmory
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WeaponData> Weapons = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> WeaponFirstObtainTimes = new();
}

[UxContract]
internal sealed class PlayerInfoBadge
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, BadgeInfo> Badges = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, BadgeInfo> HistoryBadges = new();
}

[UxContract]
internal sealed class PlayerInfoFightStyle
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> FightStyleIsUnLocked = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> FightStyleFirstUnlockTimes = new();
}

[UxContract]
internal sealed class PlayerInfoMartialArtist
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> RumorBackpack = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, MartialArtistSlotInfo> SlottedRumors = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> FinishedWuxueId = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> CompletedQuests = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> UnlockedQuests = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> PendingGossipRumors = new();
}

[UxContract]
internal sealed class PlayerInfoPokemon
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PokemonEnemy> AllPokemons = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<ulong> FastFightSquad = new();
}

[UxContract]
internal sealed class PlayerInfoPopularity
{
    public int Popularity;
    public uint NextPopularityUpdateTime;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityData> HistoryPopularityList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityData> PastDaysPopularityList = new();
    public uint TotalLeftMoney;
    public uint LastPopularityUpdateTime;
    public uint NextYesterdayAvgPopularityUpdateTime;
    public uint TodayCoinGet;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityWalletRewardData> PastHoursCoinRewards = new();
    public FanBoxDropInfo FanBoxDropInfo = new();
    public uint YesterdayCoinGet;
    public int YesterdayAvgPopularity;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityDropRecord> DropRecordList = new();
    public uint LastSettlementTime;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityDayReward> DayRewardList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityData> PastDaysHighestPopularityList = new();
    public bool IsFirstTriggered;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityHotGainEvent> HotGainEventList = new();
    public bool IsFirstPhoneOpened;
}

[UxContract]
internal sealed class PlayerInstrumentInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerGuitarInfo> GuitarInfos = new();
}

[UxContract]
internal sealed class PlayerInteractionActionInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerInteractionActionItem> UnlockActionItemDict = new();
    public bool InvitedNotDisturb;
}

[UxContract]
internal sealed class PlayerInteractionActionItem
{
    public uint CfgId;
    public uint UnlockTime;
    public bool ShowRedPoint;
}

[UxContract]
internal sealed class PlayerItemDayCount
{
    public uint TemplateId;
    public uint Count;
}

[UxContract]
internal sealed class PlayerLikeInfo
{
    public uint LastResetTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<ulong, bool> HomepageLikes = new();
}

[UxContract]
internal sealed class PlayerLinkPlanningBoardInfo
{
    public uint SelectedGameplayAttributeId;
    public uint LastRaidMultiPlayerId;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, byte> MultiPlayerIdStates = new();
}

[UxContract]
internal sealed class PlayerMatchInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> GameId2LastPlayTime = new();
    public uint LastInviteAllTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> AvailablePrepareActions = new();
    public byte DeviceLevel;
    public byte CurLinkDeviceLevel;
    public PlayerGameInfo playerGameInfo = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, RememberPrepareInfo> RememberPrepareInfos = new();
}

[UxContract]
internal sealed class PlayerMeccaGrandpaPartsInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, MeccaGrandpaPartInfo> Parts = new();
    public MeccaGrandpaBuildInfo BuildInfo = new();
}

[UxContract]
internal sealed class PlayerMonthlyPassInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, MonthlyPassInfo> MonthlyPassInfos = new();
}

[UxContract]
internal sealed class PlayerOCInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<ulong, OCInfo> OCInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<string, OCSpeechInfo> SpeechInfosDict = new();
    public ulong PreGenerateOCId;
    public OCMemoryInfo MemoryInfo = new();
    public OCMeccaGrandpaInfo OCMeccaGrandpaInfo = new();
    public uint NextFashionOCId;
}

[UxContract]
internal sealed class PlayerOnlineSeasonProgressClientInfo
{
    public uint CurrentSeasonId;
    public bool IsSeasonUnlocked;
    public uint SeasonProgress;
    public uint SeasonLevel;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> ClaimedLevelRewards = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, byte> TaskStates = new();
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerOnlineSessonTaskExtraState> ExtraTaskStates = new();
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PendingSeasonReward> PendingSeasonRewards = new();
}

[UxContract]
internal sealed class PlayerOnlineSessonTaskExtraState
{
    public uint CompleteCount;
}

[UxContract]
internal sealed class PlayerPackItem
{
    public ulong UniqueId;
    public uint TemplateId;
    public uint Count;
    public bool IsNew;
    public uint ExpiryTime;
    public byte RemindState;
    public byte Quality;
    public ulong Tags;
    public bool IsBind;
    public PlayerPackItemComponents? Components;
    public uint CDFinishTime;
}

[UxContract]
internal sealed class PlayerPackItemComponents
{
    public PlayerPackExtractionShooterComponent? ExtractionShooterItem;
    public PlayerPackCollectiblePlacedComponent? CollectiblePlaced;
    public PlayerPackGachaGrandPrizeComponent? GachaGrandPrize;
}

[UxContract]
internal sealed class PlayerPackExtractionShooterComponent
{
}

[UxContract]
internal sealed class PlayerPackCollectiblePlacedComponent
{
    public PlayerPackCollectiblePlacedInfo? PlacedInfo;
}

[UxContract]
internal sealed class PlayerPackCollectiblePlacedInfo
{
    public PlayerPackCollectibleFurnitureInfo? Furniture;
}

[UxContract]
internal sealed class PlayerPackCollectibleFurnitureInfo
{
    public uint HouseId;
    public ulong FurniturePlacedId;
    public uint FurnitureSlotId;
}

[UxContract]
internal sealed class PlayerPackGachaGrandPrizeComponent
{
    public uint Number;
}

[UxContract]
internal sealed class PlayerPhoneClientInfo
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PhoneInfos> SpiritPhoneInfos = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> DownLoadAppIds = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> TempDisabledContactIds = new();
}

[UxContract]
internal sealed class PlayerRadioSongsData
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, bool> SongInfoDict = new();
}

[UxContract]
internal sealed class PlayerScenarioInfo
{
    public string SceneName = string.Empty;
    public PlayerScenarioPublicInfo? PublicInfo;
}

[UxContract]
internal sealed class PlayerScenarioInfos
{
    public uint CurSlot;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerScenarioInfo> PlayerScenarioInfoDict = new();
}

[UxContract]
internal sealed class PlayerScenarioPublicInfo
{
    public uint SceneId;
    public string Thumbnail = string.Empty;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Rotation = new();
    public uint FieldOfView;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PlayerScenarioVehicle> Vehicles = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PlayerScenarioSpirit> Spirits = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<ScenarioSticker> Stickers = new();
    public uint FilterId;
    public int FilterStrength;
}

[UxContract]
internal sealed class PlayerScenarioSpirit
{
    public uint SpiritId;
    public byte SchemeIndex;
    public FashionCustomSuitSchemeInfo? CustomFashionInfo;
    public uint ActionType;
    public uint ActionGroup;
    public string IKType = string.Empty;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Rotation = new();
    public SpiritWearFashionsInfo? FashionInfo;
    public uint Expression;
}

[UxContract]
internal sealed class PlayerScenarioVehicle
{
    public uint VehicleId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Rotation = new();
    public PlayerVehicleDetail? VehicleInfo;
}

[UxContract]
internal sealed class PlayerSettingInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, PlayerSettingValue> SettingDict = new();
}

[UxContract]
internal sealed class PlayerSettingValue
{
    public double NumberValue;
    public string? StringValue;
}

[UxContract]
internal sealed class PlayerSingleHouseConfiguration
{
    public PlayerHouseCameraConfiguration Camera = new();
}

[UxContract]
internal sealed class PlayerTradeInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<TradeOrderRef> ActiveOrders = new();
    public uint TradeBanExpireTime;
    public uint LastListTime;
    public uint LastCancelTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> BoxCompositeProgressDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> FavoriteTradeItemIds = new();
}

[UxContract]
internal sealed class PlayerTuiteClientInfo
{
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Struct)]
    public List<ClientTuiteInfo> TuiteList = new();
}

[UxContract]
internal sealed class PlayerVehicleDetail
{
    public uint Id;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PlayerVehiclePartInfo> Parts = new();
    public uint UnlockTime;
    public uint SuitId;
}

[UxContract]
internal sealed class PlayerVehicleInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PlayerVehicleDetail> UnlockedVehicles = new();
    public int RequisitionVehicleCount;
    public uint ParkingVehicleId;
}

[UxContract]
internal sealed class PlayerVehiclePartInfo
{
    public uint VehiclePartId;
    public uint VehiclePartTag;
}

[UxContract]
internal sealed class PlayerWeaponSkinInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritWeaponSkinInfo> SpiritWeaponSkinDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> OwnedSkinIds = new();
}

[UxContract]
internal sealed class PokemonEnemy
{
    public ulong Id;
    public uint Body;
    public uint Camp;
    public uint Weapon;
    public uint LimboChaId;
    public uint AcquireTime;
    public bool IsLocked;
}

[UxContract]
internal sealed class PopularityData
{
    public uint Time;
    public int Value;
}

[UxContract]
internal sealed class PopularityWalletRewardData
{
    public uint Date;
    public uint Reward;
}

[UxContract]
internal sealed class RaidBattleUnitSpirit
{
    public OtherPlayerSpiritWearFashionsInfo? SpiritWearFashionsInfo;
    public bool Begging;
    public bool IsBot;
    public ulong Id;
    public uint TemplateId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    public float FacingDirection;
    public ulong OwnerId;
    public ulong ManagedPid;
    public byte MoveId;
    public uint NavTags;
    public MoveActionGroundData? GroundData;
}

[UxContract]
internal sealed class SceneFogMap
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<byte>? FogValue;
    public bool All;
    public int LockCnt;
    public int XSize;
    public int ZSize;
    public int TileSize;
    public int XMin;
    public int ZMin;
}

[UxContract]
internal sealed class ServerSimpleGridInfo
{
    public int MinX;
    public int MinZ;
    public int MaxX;
    public int MaxZ;
}

[UxContract]
internal sealed class SoundEffectConfig
{
    public float tempo;
    public float pitch;
    public float power;
    public float richness;
    public string? template;
}

[UxContract]
internal sealed class SpiritAbilityInfo
{
    public uint TemplateId;
    public uint Exp;
    public bool NewLevel;
    public uint ConfirmedLevel;
    public uint Level;
}

[UxContract]
internal sealed class SpiritBattleInfo
{
    public bool IsUniqueSkillLocked;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<int, float> ConsumableCounters = new();
}

[UxContract]
internal sealed class SpiritFashionsInfo
{
    public uint SpiritId;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<byte, FashionCustomSuitSchemeInfo> FashionCustomSuitSchemeInfos = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, FashionFunctionSuitSchemeInfo> FashionFunctionSuitSchemeInfoDict = new();
    public SpiritWearFashionsInfo SpiritWearFashionsInfo = new();
    public SpiritWearFashionsInfo? SpiritPrevWearFashionsInfo;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint>? FirstGainSuitIdList;
    public short ActiveClientTryWearSource;
    public byte UnlockSuitSlotCount;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> MainFashionId2VariantFashionIdDict = new();
}

[UxContract]
internal sealed class SpiritFightStyleInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> FightStyleInfo = new();
}

[UxContract]
internal sealed class SpiritGroupChatInfo
{
    public uint Id;
    public uint CreateTime;
}

[UxContract]
internal sealed class SpiritInfo
{
    public ulong Id;
    public uint TemplateId;
    public uint PossessTime;
    public float HpRate;
    public SpiritUrbanSkill SpiritUrbanSkill = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritAbilityInfo> SpiritAbilities = new();
    public SpiritJobInfo SpiritJobInfo = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, float> PermanentAddAttributes = new();
    public PlayerInfoBadge InfoBadge = new();
    public SpiritMobileSkinInfo MobileSkinInfo = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WeaponData> WeaponSlots = new();
    public bool EverSwitched;
    public SpiritBattleInfo SpiritBattleInfo = new();
    public SpiritTalentInfo TalentInfo = new();
    public SpiritFightStyleInfo SpiritFightStyle = new();
    public bool Blocked;
    public SpiritSummonAgentWheelWeaponInfo SummonAgentWheelWeaponInfo = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PlayerBuffLibraryEntry> BuffLibraryEntries = new();
    public ulong LastUsedWeaponInstanceId;
}

[UxContract]
internal sealed class SpiritInitData
{
    public ulong Id;
    public uint TemplateId;
    public bool IsActive;
    public uint WeaponTemplateId;
    public uint WeaponSkinId;
}

[UxContract]
internal sealed class SpiritJob
{
    public uint Job;
    public uint Exp;
    public byte Level;
    public uint RegisterTime;
    public uint UnregisterTime;
    public SpiritJobTalentInfo TalentInfo = new();
}

[UxContract]
internal sealed class SpiritJobInfo
{
    public uint CurrentJob;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritJob> AvailableJobs = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritJob> HistoryJobs = new();
}

[UxContract]
internal sealed class SpiritJobTalentInfo
{
    public uint TalentPoint;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritOrJobTalentNodeInfo> UnlockTalentInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, TalentTreeRecord> TalentTreeRecordDict = new();
}

[UxContract]
internal sealed class SpiritMobileSkinInfo
{
    public uint Wallpaper;
    public uint Decoration;
    public uint Pendant;
}

[UxContract]
internal sealed class SpiritOrJobTalentNodeInfo
{
    public uint TalentId;
    public uint Layer;
}

[UxContract]
internal sealed class SpiritPanelData
{
    public uint FightSpiritId;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, float> UrbanAttrs = new();
    public float MaxHp;
    public float Dam;
    public float DefDeduct;
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, float> Attrs = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, float> NakedAttrs = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public Dictionary<uint, float> ConsumableAttrs = new();
}

[UxContract]
internal sealed class SpiritSummonAgentWheelWeaponInfo
{
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SummonAgentWheelWeaponInfo> WheelWeaponInfos = new();
}

[UxContract]
internal sealed class SpiritTalentInfo
{
    public uint Exp;
    public uint Level;
    public uint TalentPoint;
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, SpiritOrJobTalentNodeInfo> UnlockTalentInfoDict = new();
    [UxCollection(Count = UxCountEncoding.Int32, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, TalentTreeRecord> TalentTreeRecordDict = new();
}

[UxContract]
internal sealed class SpiritUrbanSkill
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<int> UrbanAbilities = new();
}

[UxContract]
internal sealed class SpiritWeaponSkinInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> SkinDict = new();
}

[UxContract]
internal sealed class SpiritWearFashionsInfo
{
    public uint FunctionSuitId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public WearSourceInfo WearSourceInfo = new();
    public bool IsTryWear;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionInfo> WearFashionInfoList = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WearFashionEditInfo>? WearFashionEditInfoList;
    public byte HiddenParts;
    public byte EditedHiddenParts;
}

[UxContract]
internal sealed class SubmitItemData
{
    public uint SubmittedCount;
    public uint LastSubmitTime;
    public uint NextResetTime;
}

[UxContract]
internal sealed class SummonAgentWheelWeaponInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> Weapons = new();
}

[UxContract]
internal sealed class TalentTreeRecord
{
    public uint SpentTalentPoint;
    public uint ActivatedNodeCount;
}

[UxContract]
internal sealed class TradeOrderRef
{
    public uint Count;
    public uint ExpireTime;
    public byte State;
    public uint ListTime;
    public TradeItemExtraData? ItemExtraData;
    public ulong OrderId;
    public uint TradeItemId;
    public uint Price;
    public uint PageIndex;
}

[UxContract]
internal sealed class TrustNpcInfo
{
    public uint ProfileId;
    public uint TrustValue;
    public uint ActivateTime;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> GotRewardList = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> FinishTargetList = new();
    public bool IsNew;
    public bool IsMaxTrustReward;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<TrustNpcTargetState> TargetStateList = new();
}

[UxContract]
internal sealed class TrustNpcTargetState
{
    public uint TargetId;
    public bool IsNew;
}

[UxContract]
internal sealed class TuiteTimelineData
{
    public uint Id;
    public string TimelineData = string.Empty;
}

[UxContract]
internal sealed class UXVector2Int
{
    public int X;
    public int Y;
}

[UxContract]
internal sealed class UXVector3
{
    public float X;
    public float Y;
    public float Z;
}

[UxContract]
internal sealed class FishPlacedInfo
{
    public FishPlacedFurnitureInfo? Furniture;
}

[UxContract]
internal sealed class FishPlacedFurnitureInfo
{
}

[UxContract]
internal sealed class TradeItemExtraData
{
    public uint VisibleAfterTime;
    public ulong FashionSuitInstanceId;
}

[UxContract]
internal sealed class WeaponEnchantSlot
{
    public uint EnchantConfigId;
}

[UxContract]
internal sealed class ClientFactionInfo
{
    [UxCollection(Count = UxCountEncoding.Int7, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<FactionEncroachmentInfo> EncroachmentInfos = new();
    [UxCollection(Count = UxCountEncoding.Int7)]
    public List<uint> FilledFactionArea = new();
}

[UxContract]
internal sealed class FactionEncroachmentInfo
{
    public uint AreaId;
    public uint AttackerFactionId;
    public uint DefenderFactionId;
    public byte State;
}

[UxContract]
internal sealed class FactionCounterAttackData
{
    public float CurValue;
    public int RemainingTickTimeSec;
    public uint BossFailCount;
}

[UxContract]
internal sealed class RememberPrepareInfo
{
    public uint VehicleId;
    public uint SpiritId;
}

[UxContract]
internal sealed class FashionSuitInstanceInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<ulong> SuitInstanceIdList = new();
    public uint GainTime;
}

[UxContract]
internal sealed class PlayerBasketballAppearanceInfo
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> EquippedDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> ExpiryDict = new();
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, uint> PendingRemoveDict = new();
}

[UxContract]
internal sealed class BeggarAiPainting
{
    public string ObjectKey = string.Empty;
    public uint CreateTime;
    public string Name = string.Empty;
    public bool IsAiPolished;
}

[UxContract]
internal sealed class PlayerChatInfo
{
    [UxCollection(Count = UxCountEncoding.Int7, ValueObjectEncoding = UxObjectEncoding.Complex)]
    public Dictionary<uint, BubbleUnlockInfo> UnlockBubbles = new();
    public uint SelectedBubble;
}

[UxContract]
internal sealed class BubbleUnlockInfo
{
    public uint Id;
    public uint GetTime;
}

[UxContract]
internal sealed class ScenarioSticker
{
    public uint StickerId;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Position = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Rotation = new();
    public float ScaleX;
    public float ScaleY;
    public uint Mode;
}

[UxContract]
internal sealed class GachaDrawRecord
{
    public uint GachaId;
    public uint PoolContentId;
    public uint DropId;
    public long DrawTimeUnix;
}

[UxContract]
internal sealed class NpcProfileWebProgress
{
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> GotProgressRewardList = new();
}

[UxContract]
internal sealed class FishRecordInfo
{
    public uint FirstCatchTime;
    public uint FirstCatchSpot;
    public float BestWeight;
    public float BestLength;
}

[UxContract]
internal sealed class HouseMetadata
{
    public uint HouseId;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<int, int> Flags = new();
}

[UxContract]
internal sealed class PopularityDropRecord
{
    public uint Time;
    public uint DropId;
    public int Popularity;
}

[UxContract]
internal sealed class PopularityRewardItem
{
    public uint Id;
    public int FanCount;
    public uint CoinCount;
    public bool IsReward;
}

[UxContract]
internal sealed class PopularityDayReward
{
    public uint Time;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<PopularityRewardItem> RewardList = new();
}

[UxContract]
internal sealed class PopularityHotGainEvent
{
    public uint Time;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public Dictionary<uint, int> TaskCompleteCountDict = new();
}

[UxContract]
internal sealed class GiftPaidItem
{
    public uint TemplateId;
    public uint Count;
    public byte Quality;
    public ulong Tags;
    public bool IsBind;
    public GiftPaidItemComponents? Components;
}

[UxContract]
internal sealed class GiftPaidItemComponents
{
}

[UxContract]
internal sealed class ExtractionShooterSetTrackInfo
{
    public uint LastAddTime;
}

[UxContract]
internal sealed class ExtractionShooterCollectionBook
{
    public uint Level;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<uint> AffixList = new();
    public uint DyeColorCount;
    public uint DyeEffectCount;
}

[UxContract]
internal sealed class WeaponBulletDatas
{
    public uint BulletId;
}

[UxContract(TypeMark = 1)]
internal sealed class WeaponData
{
    public uint TemplateId;
    public int Durability;
    public ulong InstanceId;
    public uint EventId;
    public double ReceivedTimeStamp;
    public uint OperatorFlags;
    public string? SpecialLabel;
    public WeaponDataFlags WeaponFlags = new();
    public float SceneItemHp;
    public int StackCount;
    public WeaponBulletDatas BulletDatas = new();
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WeaponDecorationDatas> Decorations = new();
    public uint FightStyleId;
    public int MagazineAmmo;
    public ulong BindPid;
    public bool IsPlayerLocked;
    [UxCollection(Count = UxCountEncoding.Int32, ItemObjectEncoding = UxObjectEncoding.Complex)]
    public List<WeaponEnchantSlot> EnchantSlots = new();
    public uint NonDirectionalEnchantCount;
    public uint DirectionalEnchantCountSinceLastNonDir;
    public uint LockedDirectionalEnhancementId;
}

[UxContract]
internal sealed class WeaponDataFlags
{
    public bool IsTaskWheelWeapon;
    public bool ShowRedDot;
    [UxCollection(Count = UxCountEncoding.Int32)]
    public List<int>? AdditionalEffectIds;
}

[UxContract]
internal sealed class WeaponDecorationDatas
{
    public ulong ItemId;
    public uint DecorationId;
}

[UxContract]
internal sealed class WearFashionEditInfo
{
    public uint FashionId;
    public float Scale;
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Rotation = new();
    [UxObject(Encoding = UxObjectEncoding.Struct)]
    public UXVector3 Offset = new();
}

[UxContract]
internal sealed class WearFashionInfo
{
    public uint FashionId;
}

[UxContract]
internal sealed class WearSourceInfo
{
    public short Source;
    public uint SourceId;
}
